version: '3'
services:
  php-apache-environment:
    container_name: php-apache-redhost
    build:
      context: ./.docker
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - '.:/var/www/html'
    ports:
      - '8080:80'
    networks:
      - sail
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "b1b3yq2"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "redhost"
      MYSQL_USER: "redhost"
      MYSQL_PASSWORD: "b1b3yq2"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sail-mysql:/var/lib/mysql'
    networks:
      - sail
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p b1b3yq2" ]
      retries: 3
      timeout: 5s
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '81:80'
    restart: always
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sail-mysql:
    driver: local
